// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MvcStore.Admin.BasicReporting {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Content MainContentContent;
		
		protected MvcStore.Admin.UserControls.SectionLevelTutorialListing SectionLevelTutorialListing1;
		
		public new MvcStore.Admin.Site Master {
			get {
				return ((MvcStore.Admin.Site)(base.Master));
			}
		}
	}
}
