// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MvcStore.Admin.ProductManagement {
	
	
	public partial class Categories {
		
		protected System.Web.UI.WebControls.Content MainContentContent;
		
		protected System.Web.UI.WebControls.ObjectDataSource CategoriesGridDataSource;
		
		protected System.Web.UI.WebControls.ObjectDataSource CategoryDetailsDataSource;
		
		protected System.Web.UI.WebControls.DetailsView CategoryDetailsView;
		
		protected System.Web.UI.WebControls.GridView CategoriesGridView;
		
		public new MvcStore.Admin.Site Master {
			get {
				return ((MvcStore.Admin.Site)(base.Master));
			}
		}
	}
}
